twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        params: '@App\Model\ParamModel'
    form_themes:
        - '@SonataCore/Form/datepicker.html.twig'